name: 'Packages Split'

on:
    workflow_dispatch: null
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                name:
                    - rekapager-api-platform
                    - rekapager-bundle
                    - rekapager-contracts
                    - rekapager-core
                    - rekapager-doctrine-collections-adapter
                    - rekapager-doctrine-orm-adapter
                    - rekapager-pagerfanta-adapter
                    - rekapager-keyset-pagination
                    - rekapager-offset-pagination
                    - rekapager-symfony-bridge
    
        steps:
            -   uses: actions/checkout@v4

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    package_directory: 'packages/${{ matrix.name }}'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    repository_organization: 'rekalogika'
                    repository_name: '${{ matrix.name }}'

                    # [optional, with "github.com" as default]
                    repository_host: github.com

                    # ↓ the user signed under the split commit
                    user_name: "Priyadi Iman Nurcahyo"
                    user_email: "1102197+priyadi@users.noreply.github.com"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: "danharrin/monorepo-split-github-action@v2.3.0"
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/easy-coding-standard" directory
                    package_directory: 'packages/${{ matrix.name }}'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    repository_organization: 'rekalogika'
                    repository_name: '${{ matrix.name }}'

                    # [optional, with "github.com" as default]
                    repository_host: github.com

                    # ↓ the user signed under the split commit
                    user_name: "Priyadi Iman Nurcahyo"
                    user_email: "1102197+priyadi@users.noreply.github.com"
